In [6]:
import pandas as pd
import numpy as np

In [ ]:
df_item_refunds=pd.read_csv('/Users/keneskenesbay/Documents/project_1/Maven+Fuzzy+Factory/order_item_refunds.csv')
df_order_items=pd.read_csv('/Users/keneskenesbay/Documents/project_1/Maven+Fuzzy+Factory/order_items.csv')
df_order=pd.read_csv('/Users/keneskenesbay/Documents/project_1/Maven+Fuzzy+Factory/orders.csv')
df_products=pd.read_csv('/Users/keneskenesbay/Documents/project_1/Maven+Fuzzy+Factory/products.csv')
df_websitepage_view=pd.read_csv('/Users/keneskenesbay/Documents/project_1/Maven+Fuzzy+Factory/website_pageviews.csv')
df_website_sessions=pd.read_csv('/Users/keneskenesbay/Documents/project_1/Maven+Fuzzy+Factory/website_sessions.csv')

In [8]:
#Checking sum of NA values in the dataframes
display("df item refunds",df_item_refunds.isna().sum(),
       "df order items",df_order_items.isna().sum(),
       "df order",df_order.isna().sum(),
       "df products",df_products.isna().sum(),
       "df websitepage view ",df_websitepage_view.isna().sum(),
       "df website sessions",df_website_sessions.isna().sum())

'df item refunds'

order_item_refund_id    0
created_at              0
order_item_id           0
order_id                0
refund_amount_usd       0
dtype: int64

'df order items'

order_item_id      0
created_at         0
order_id           0
product_id         0
is_primary_item    0
price_usd          0
cogs_usd           0
dtype: int64

'df order'

order_id              0
created_at            0
website_session_id    0
user_id               0
primary_product_id    0
items_purchased       0
price_usd             0
cogs_usd              0
dtype: int64

'df products'

product_id      0
created_at      0
product_name    0
dtype: int64

'df websitepage view '

website_pageview_id    0
created_at             0
website_session_id     0
pageview_url           0
dtype: int64

'df website sessions'

website_session_id        0
created_at                0
user_id                   0
is_repeat_session         0
utm_source            83328
utm_campaign          83328
utm_content           83328
device_type               0
http_referer          39917
dtype: int64

In [9]:
#Checking sum of the duplicated values in the dataFrames
display("df item refunds",df_item_refunds.duplicated().sum(),
       "df order items",df_order_items.duplicated().sum(),
       "df order",df_order.duplicated().sum(),
       "df products",df_products.duplicated().sum(),
       "df websitepage view ",df_websitepage_view.duplicated().sum(),
       "df website sessions",df_website_sessions.duplicated().sum())

'df item refunds'

np.int64(0)

'df order items'

np.int64(0)

'df order'

np.int64(0)

'df products'

np.int64(0)

'df websitepage view '

np.int64(0)

'df website sessions'

np.int64(0)

In [10]:
#Checking sum of the duplicate values in primary key of the dataFrames
display(df_item_refunds["order_item_refund_id"].duplicated().sum(),
df_order_items["order_item_id"].duplicated().sum(),
df_order["order_id"].duplicated().sum(),
df_products["product_id"].duplicated().sum(),
df_websitepage_view["website_pageview_id"].duplicated().sum(),
df_website_sessions["website_session_id"].duplicated().sum())

np.int64(0)

np.int64(0)

np.int64(0)

np.int64(0)

np.int64(0)

np.int64(0)

In [13]:
#checking the data types of dataFrames
display(df_item_refunds.info(),
        df_order_items.info(),
        df_order.info(),
        df_products.info(),
        df_websitepage_view.info(),
        df_website_sessions.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   datetime64[ns]
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: datetime64[ns](1), float64(1), int64(3)
memory usage: 67.7 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  datetime64[ns]
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(4)
memory usage: 2.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  datetime64[ns]
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: datetime64[ns](1), float64(2), int64(5)
memory usage: 2.0 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   created_at    4 non-null      datetime64[ns]
 2   product_name  4 non-null      object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 228.0+ bytes
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188124 entries, 0 to 1188123
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1188124 non-null  int64
 1   created_at           1188124 non-null  datetime64[ns]
 2   website_session_id   1188124 non-null  int64
 3   pageview_url         1188124 non-null  object
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 36.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  datetime64[ns]
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: datetime64[ns](1), int64(3), object(5)
memory usage: 32.5+ MB

None

None

None

None

None

None

In [12]:
#Change types of dataframes to the correct 
df_item_refunds['created_at']=pd.to_datetime(df_item_refunds['created_at'])
df_order_items['created_at']=pd.to_datetime(df_order_items['created_at'])
df_order['created_at']=pd.to_datetime(df_order['created_at'])
df_products['created_at']=pd.to_datetime(df_products['created_at'])
df_websitepage_view['created_at']=pd.to_datetime(df_websitepage_view['created_at'])
df_website_sessions['created_at']=pd.to_datetime(df_website_sessions['created_at'])

In [14]:
#Checking are there any negative numbers in the order prices?
display(
    (df_order['price_usd']<0).sum(),
    (df_order['cogs_usd']<0).sum()
)

np.int64(0)

np.int64(0)

In [15]:
display(df_order,df_order_items)

,order_id,created_at,website_session_id,user_id,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49
...,...,...,...,...,...,...,...,...
32308,32309,2015-03-19 03:58:12,472795,394255,1,1,49.99,19.49
32309,32310,2015-03-19 04:10:43,472798,394257,4,1,29.99,9.49
32310,32311,2015-03-19 05:27:28,472809,394268,2,2,89.98,31.98
32311,32312,2015-03-19 05:35:57,472814,394273,4,1,29.99,9.49
32312,32313,2015-03-19 05:38:31,472818,386000,1,1,49.99,19.49

,order_item_id,created_at,order_id,product_id,is_primary_item,price_usd,cogs_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49
...,...,...,...,...,...,...,...
40020,40021,2015-03-19 04:10:43,32310,4,1,29.99,9.49
40021,40022,2015-03-19 05:27:28,32311,2,1,59.99,22.49
40022,40023,2015-03-19 05:27:28,32311,4,0,29.99,9.49
40023,40024,2015-03-19 05:35:57,32312,4,1,29.99,9.49
40024,40025,2015-03-19 05:38:31,32313,1,1,49.99,19.49

In [16]:
#Check the correctness of table relationships (FK)

invalid_orders=~df_order_items['order_id'].isin(df_order['order_id'])
invalid_website_sessions=~df_order['website_session_id'].isin(df_website_sessions['website_session_id'])
invalid_product_id=~df_order_items['product_id'].isin(df_products['product_id'])

display(
    invalid_orders.sum(),
    invalid_website_sessions.sum(),
    invalid_product_id.sum()
)

np.int64(0)

np.int64(0)

np.int64(0)

In [17]:
#Check the correctness of dates
display(
    df_order['created_at'].min(),
    df_order['created_at'].max()
)

Timestamp('2012-03-19 10:42:46')

Timestamp('2015-03-19 05:38:31')

 <h1> Data quality summary :</h1> <br>
<h3> 1.No missing values were detected across al tables</h3> <br>
<h3>2.No duplicate rows were detected </h3><br>
<h3>3.All primary keys are unique </h3><br>
<h3>4.Data types was reviewed and 'created_at' was convert to the correct data type</h3> <br>
<h3>5.No negative values were found in 'price_usd' and 'cogs_usd' </h3><br>
<h3>6.Foreign keys relationships are valid </h3><br>
<h3>7.Data ranges consistent and does not had future dates,so data ranges correct </h3><br>

<h1>Overal:The datasets passed the initial data quality assessment and are ready for exploratory data analysis (EDA).</h1> <br>